@port = 3000
@host = http://localhost:{{port}}


###
GET {{host}}/api/proyectos/

###
GET {{host}}/api/proyectos/categoria/angular

###
POST {{host}}/api/proyectos/
Content-Type: application/json

{
    "titulo": "Peqar de cursos",
    "descripcion":"Creación de una API de cursos online enfocado a alumnos y profesores. En el apartado de alumnos pordemos registrarnos, apuntarnos a los cursos que deseemos hacer, realizar las lecciones mientras se va sumando el pocentaje realizado y finalmente superar el examen que te indicará si has aprobado o suspendido. En el apartado de profesores podemos registrarnos, crear examenes y administrar todo lo realicionado con el alumno. ",
    "cliente":"IdBootcamp",
    "categoria":"MySQL, Angular 17"
}

###
PUT {{host}}/api/proyectos/663623621bfc3b9a0d0191c3
Content-Type: application/json

{
    "titulo": "proyecto editado ruben",
    "descripcion":"Edicion",
    "cliente":"Google",
}

###
DELETE {{host}}/api/proyectos/663623621bfc3b9a0d0191c3

